/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-30-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
//Account trigger handler class use TriggerHandlerBoiler template 
public with sharing class AccountTriggerHandler {
    
    public static void beforeInsert(List<Account> triggerNew) {
        //logic for before insert
    }

    public static void afterInsert(List<Account> triggerNew) {
        //logic for after insert
    }    
}